# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import build_orders_pb2 as build__orders__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in build_orders_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BuildOrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOrder = channel.unary_unary(
                '/buildorders.BuildOrderService/SendOrder',
                request_serializer=build__orders__pb2.BuildOrder.SerializeToString,
                response_deserializer=build__orders__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.FinishUpload = channel.unary_unary(
                '/buildorders.BuildOrderService/FinishUpload',
                request_serializer=build__orders__pb2.FinishRequest.SerializeToString,
                response_deserializer=build__orders__pb2.StatusResponse.FromString,
                _registered_method=True)


class BuildOrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuildOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOrder,
                    request_deserializer=build__orders__pb2.BuildOrder.FromString,
                    response_serializer=build__orders__pb2.StatusResponse.SerializeToString,
            ),
            'FinishUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishUpload,
                    request_deserializer=build__orders__pb2.FinishRequest.FromString,
                    response_serializer=build__orders__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buildorders.BuildOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('buildorders.BuildOrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BuildOrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buildorders.BuildOrderService/SendOrder',
            build__orders__pb2.BuildOrder.SerializeToString,
            build__orders__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buildorders.BuildOrderService/FinishUpload',
            build__orders__pb2.FinishRequest.SerializeToString,
            build__orders__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
